version: "3.2"

networks:
  tasks_mg_project_1:

services:

  nginx_base:
    container_name: nginx_base
    # image: 8c1bfa967ebf
    image: nginx:stable-alpine
    ports:
      - "85:80"
    volumes:  
      - ./app:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_base
      - mysql_base
    networks:
      - tasks_mg_project_1

  php_base:
    container_name: php_base
#    image: 15d55c4fd75d
    build:
      context: './php/'
#      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/sf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini-production
    networks:
      - tasks_mg_project_1  

  mysql_base:
    container_name: mysql_base
    image: mysql
    # image: c8562eaf9d81
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_PASSWORD: pwd
    networks:
      - tasks_mg_project_1  

  phpmyadmin_base:
    container_name: phpmyadmin_base
    image: phpmyadmin/phpmyadmin
    # image: 6f9550cff175
    restart: always
    environment:
      PMA_HOST: mysql_base
      PMA_USER:  root
      PMA_PASSWORD: pwd
    ports:
      - "8080:80"
    networks:
      - tasks_mg_project_1     