version: "3.2"

services:

  php_sf:
    container_name: php_sf
#    image: 15d55c4fd75d
    build:
      context: './php/'
#      dockerfile: ./php/Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./app:/var/www/sf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini-production

  mysql_sf:
    container_name: mysql_sf
    image: mysql
    # image: e3fcc9e1cc04
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_PASSWORD: pwd

  nginx_sf2:
    container_name: nginx_sf2
    # image: 8c1bfa967ebf
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_sf
      - mysql_sf

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   # image: 6f9550cff175
  #   restart: always
  #   environment:
  #     PMA_HOST: mysql_sf
  #     PMA_USER:  root
  #     PMA_PASSWORD: pwd
  #   ports:
  #     - "8080:80"